apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    app: {{ include "web.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "web.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "web.fullname" . }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: 
              value: "http://$(NODE_IP):{{ .Values.service.apiPort }}/"
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
