replicaCount: 1
image:
  repository: hieubeo2369/web
  tag: v1.0.1-env
  pullPolicy: IfNotPresent
#thêm haproxy
haproxy:
  image: haproxy:latest
  port: 443
  sslSecretName: haproxy-ssl

service:
  type: NodePort
# port: 3000 
  port: 443
  nodePort: 30001
  apiPort: 30002
ingress:
  enabled: false
  # annotations:
  #   nginx.ingress.kubernetes.io/ssl-redirect: "true"
  # hosts:
  #   - host: vdt.local
  #     paths: 
  #       - path: /web
  #         pathType: ImplementationSpecific
  # tls:
  #   - secretName: web-tls
  #     hosts:
  #       - vdt.local
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount:
  create: true
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
