replicaCount: 1
image:
  repository: hieubeo2369/web
  tag: v1.0.1-env
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 3000
  nodePort: 30001
  apiPort: 30002
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: 192-168-49-2.nip.io
      paths:
        - path: /web
          pathType: Prefix
  tls:
    - secretName: tls-secret
      hosts:
        - 192-168-49-2.nip.io
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount:
  create: true
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
